services:
  app:
    image: php:8.2-cli-alpine
    command: php -S 0.0.0.0:8080 -t /var/www/html/public
    ports:
      - ${APP_PORT:-8080}:8080
    volumes:
      - '.:/var/www/html'
    depends_on:
      - db
    networks:
      - promo

  db:
    image: mysql:8
    ports:
      - ${DATABASE_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - promo

volumes:
  db-data:
    driver: local

networks:
  promo:
    driver: bridge
